# Generated by Django 4.0.5 on 2022-06-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='sex',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
